### ISSUE TITLE
Changes to a sass_file() are false positively cached

### ISSUE THREAD

**Issue by cpsievert** [rstudio/sass#107]
If you run this code once, then change the contents of `styles.scss`, the styles don't update. This issue was likely introduced by #98

```r
library(htmltools)
library(sass)
library(bslib)
library(shiny)

options(sass.cache = TRUE)

ui <- tags$body(
  tags$style(HTML(sass(sass_bundle(sass_layer(rules = sass_file("styles.scss")))))),
  "Hello"
)

browsable(ui)
```

```scss
// styles.scss
body {background-color: blue}
```
